<?php
echo '
<div id="secondarycontent">

	<!-- secondary content start -->
		
	<div class="content">
	        <a href="http://www.iiit.ac.in"><img src="/whereismybus/images/pic2.jpg" class="picC" alt="" /></a>
	</div>
		
	<h3>Services</h3>
	<div class="content">
		<ul class="linklist">
			<!-- <li class="first"><a href="/whereismybus/feedback.php">Complaints and Feedback</a></li> -->
			<li class="first"><a href="https://docs.google.com/spreadsheet/viewform?formkey=dHpDU0d6Tk52M1hCRkt1a2xLeXJxQkE6MQ">Complaints and Feedback</a></li>
			<li><a href="/whereismybus/contact.php">About us</a></li>
		</ul>
	</div>
        <h3>Important Links</h3>
	<div class="content">
		<ul class="linklist">
			<li class="first"><a href="http://www.iiit.ac.in">IIIT, Hyderabad</a></li>
			<li><a href="http://www.facebook.com/groups/208229335907009/">Join us on Facebook</a></li>   
		</ul>
	</div>
	<!-- secondary content end -->
</div>
	
';
?>
